# Use root/admin as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      SQLDATA: /data/mysql
    volumes:
      - mysql:/data/mysql

  adminer:
    image: adminer
    ports:
      - 8000:8080
