version: '3'

services:
  db1:
    image: couchbase
    container_name: db1

  db2:
    image: couchbase
    container_name: db2

  db3:
    image: couchbase
    container_name: db3
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"


